from pathlib import Path
p=Path('/mnt/data/portfolio_v8/Portfolio-Malek-Klimane-V7/style.css')
s=p.read_text()
s += r'''

/* ===== V8 — cleaner visual system + deeper interactions ===== */
.company-line,.school-logo,.revime-logo{display:none!important}
.edu-card{display:block;padding:24px 26px;min-height:160px}.edu-card span{display:inline-block;color:#ff6573;font:600 9px 'JetBrains Mono';letter-spacing:.08em;margin-bottom:10px}.edu-card h3{margin:0 0 6px}.edu-card p{margin:0 0 7px;color:#8994a4}.edu-card small{color:#687486;font:500 10px 'JetBrains Mono'}
.cert-card{transition:transform .25s ease,border-color .25s ease,box-shadow .25s ease}.cert-card:hover{transform:translateY(-5px);border-color:rgba(255,51,71,.34);box-shadow:0 22px 70px rgba(0,0,0,.28)}
.cert-topline{display:flex;justify-content:space-between;gap:10px;align-items:center}.cert-status{font:600 8px 'JetBrains Mono';letter-spacing:.08em;color:var(--green);border:1px solid rgba(85,223,139,.25);padding:6px 8px}.cert-meter{display:flex;align-items:center;gap:10px;margin:18px 0 12px}.cert-meter span{height:5px;background:#171e28;flex:1;overflow:hidden}.cert-meter span i{height:100%;display:block;background:linear-gradient(90deg,var(--red),#ff6573);transform-origin:left}.cert-meter b{font:600 8px 'JetBrains Mono';color:#657184;white-space:nowrap}.cert-toggle{appearance:none;border:1px solid var(--line);background:#0a0f16;color:#dce1e7;padding:9px 11px;font:600 9px 'JetBrains Mono';cursor:pointer;transition:.2s}.cert-toggle:hover{border-color:var(--red);background:rgba(255,51,71,.07)}.cert-toggle span{display:inline-block;margin-left:8px;color:var(--red);font-size:13px}.cert-details{display:grid;grid-template-columns:1fr 1fr;gap:8px;max-height:0;overflow:hidden;opacity:0;transition:max-height .4s ease,opacity .25s ease;margin-top:0}.cert-details.open{max-height:650px;opacity:1;margin-top:14px}.cert-details>div{border:1px solid var(--line);background:#080d13;padding:12px}.cert-details b{font:600 9px 'JetBrains Mono';color:#dfe4ea}.cert-details p{font-size:11px!important;color:#778394!important;margin:6px 0 0!important}.room-card{position:relative;overflow:hidden}.room-card:after{content:'OPEN';position:absolute;right:9px;bottom:8px;color:#4f5b6d;font:600 7px 'JetBrains Mono';opacity:0;transform:translateY(3px);transition:.2s}.room-card:hover:after{opacity:1;transform:none}.room-card strong{padding-right:25px}.room-modal{position:fixed;inset:0;z-index:1100;display:grid;place-items:center;padding:24px;background:rgba(2,5,9,.86);backdrop-filter:blur(12px);opacity:0;pointer-events:none;transition:opacity .2s}.room-modal.open{opacity:1;pointer-events:auto}.room-modal-panel{width:min(620px,94vw);background:linear-gradient(145deg,#111821,#080d13);border:1px solid rgba(255,51,71,.35);box-shadow:0 40px 120px rgba(0,0,0,.6);padding:30px;position:relative;transform:translateY(12px);transition:transform .25s}.room-modal.open .room-modal-panel{transform:none}.room-modal-close{position:absolute;right:14px;top:14px;width:34px;height:34px;border:1px solid var(--line);background:#090e15;color:#fff;font-size:19px;cursor:pointer}.room-modal-kicker{color:#ff6573;font:600 8px 'JetBrains Mono';letter-spacing:.13em}.room-modal h3{font:700 38px/1.05 'Space Grotesk';margin:18px 0 15px}.room-modal-meta{display:flex;gap:8px;flex-wrap:wrap}.room-modal-meta>*{padding:7px 9px;border:1px solid var(--line);font:600 8px 'JetBrains Mono';color:#8792a1}.room-modal-meta b{color:#55df8b}.room-modal p{color:#929cab;font-size:14px;line-height:1.7}.room-modal-tags{display:flex;gap:7px;flex-wrap:wrap}.room-modal-tags span{border:1px solid var(--line);padding:7px 9px;color:#aeb7c4;font:500 9px 'JetBrains Mono'}
@media(max-width:620px){.cert-details{grid-template-columns:1fr}.cert-topline{align-items:flex-start}.cert-status{display:none}.room-modal-panel{padding:24px}.room-modal h3{font-size:31px}}
'''
p.write_text(s)
