from pathlib import Path
p=Path('/mnt/data/portfolio_v8/Portfolio-Malek-Klimane-V7/index.html')
s=p.read_text()
# remove standalone company/school/project logos
s=s.replace('<div class="company-line"><div class="company-logo text-logo ratp-logo">RATP<br><small>CAP</small></div><div><h3>Technicien Supérieur en Électronique — Stage + 4 CDD</h3><b>RATP CAP · Paris</b></div></div>', '<div><h3>Technicien Supérieur en Électronique — Stage + 4 CDD</h3><b>RATP CAP · Paris</b></div>')
s=s.replace('<div class="company-line"><div class="company-logo text-logo cardy-logo">CARDY</div><div><h3>Community Manager</h3><b>CARDY · CDD</b></div></div>', '<div><h3>Community Manager</h3><b>CARDY · CDD</b></div>')
s=s.replace('<div class="school-logo"><img src="assets/logo-chaptal.jpeg" alt="Lycée Chaptal"></div>', '')
s=s.replace('<div class="school-logo"><img src="assets/logo-schola-nova.jpeg" alt="Schola Nova"></div>', '')
s=s.replace('<div class="school-logo"><img src="assets/logo-pstb.png" alt="Paris School of Technology & Business"></div>', '')
s=s.replace('<img class="revime-logo" src="assets/revime-logo.png" alt="REVIME">','')
# remove duplicate Secursense rack image, keep one
s=s.replace('<figure class="wide"><img src="assets/secursense-racks-2.png" alt="Infrastructure et équipements réseau chez Secursense"><figcaption>Racks, câblage et équipements</figcaption></figure>','')
# correct THM web count
s=s.replace('data-filter="web">Web <span>9</span>', 'data-filter="web">Web <span>11</span>')
# replace certification block
old='''<article class="cert-card featured-cert"><div class="cert-image"><img src="assets/centri-blue-team.jpg" alt="CENTRI Blue Team Junior Analyst"><span>2026</span></div><div class="cert-info"><small>CENTRI</small><h3>Blue Team Junior Analyst</h3><p>Parcours pratique d'entrée de gamme validant des connaissances et une capacité pratique autour de plusieurs domaines de sécurité.</p><div class="cert-modules"><b>OSINT</b><b>Digital Forensics</b><b>Vulnerability Management</b><b>Dark Web Operations</b><b>Threat Hunting</b><b>Network Analysis</b></div><a href="assets/centri-blue-team.jpg" target="_blank">Voir le certificat ↗</a></div></article>
<article class="cert-card"><div class="cert-image"><img src="assets/fortinet-cloud.jpg" alt="Fortinet Cybersecurity and Cloud Fundamentals 1.0"><span>2026</span></div><div class="cert-info"><small>FORTINET TRAINING INSTITUTE</small><h3>Cybersecurity &amp; Cloud Fundamentals 1.0</h3><p>Fondamentaux de cybersécurité et de cloud, avec une approche de découverte des enjeux de sécurité des environnements modernes.</p><div class="cert-modules"><b>Cybersecurity fundamentals</b><b>Cloud fundamentals</b><b>Security concepts</b></div><a href="assets/fortinet-cloud.jpg" target="_blank">Voir le certificat ↗</a></div></article>'''
new='''<article class="cert-card featured-cert interactive-cert"><div class="cert-image"><img src="assets/centri-blue-team.jpg" alt="CENTRI Blue Team Junior Analyst"><span>2026</span></div><div class="cert-info"><div class="cert-topline"><small>CENTRI · BLUE TEAM JUNIOR ANALYST</small><b class="cert-status">COMPLETED</b></div><h3>Blue Team Junior Analyst</h3><p>Training pathway pratique d'entrée de gamme. Le certificat indique six domaines travaillés : OSINT, digital forensics, vulnerability management, dark web operations, threat hunting et network analysis.</p><div class="cert-meter"><span><i style="width:100%"></i></span><b>6 / 6 domaines</b></div><button class="cert-toggle" type="button" aria-expanded="false">Explorer le contenu <span>+</span></button><div class="cert-details"><div><b>01 · OSINT</b><p>Collecte et analyse d'informations issues de sources ouvertes.</p></div><div><b>02 · Digital Forensics</b><p>Premiers réflexes d'investigation et d'analyse de traces numériques.</p></div><div><b>03 · Vulnerability Management</b><p>Identification, analyse et suivi des vulnérabilités.</p></div><div><b>04 · Dark Web Operations</b><p>Compréhension des environnements clear, deep et dark web.</p></div><div><b>05 · Threat Hunting</b><p>Recherche proactive et analyse de signes de menace.</p></div><div><b>06 · Network Analysis</b><p>Analyse du trafic réseau et compréhension des communications.</p></div></div><a href="assets/centri-blue-team.jpg" target="_blank">Voir le certificat ↗</a></div></article>
<article class="cert-card interactive-cert"><div class="cert-image"><img src="assets/fortinet-cloud.jpg" alt="Fortinet Cybersecurity and Cloud Fundamentals 1.0"><span>2026</span></div><div class="cert-info"><div class="cert-topline"><small>FORTINET TRAINING INSTITUTE · COURSE COMPLETION</small><b class="cert-status">COMPLETED</b></div><h3>Cybersecurity &amp; Cloud Fundamentals 1.0</h3><p>Formation officielle Fortinet consacrée aux fondamentaux de la cybersécurité et du cloud. Elle introduit les concepts et technologies nécessaires pour poursuivre vers des parcours de sécurité plus avancés.</p><div class="cert-meter"><span><i style="width:100%"></i></span><b>COURSE COMPLETED</b></div><button class="cert-toggle" type="button" aria-expanded="false">Explorer le contenu <span>+</span></button><div class="cert-details"><div><b>Cybersecurity fundamentals</b><p>Comprendre les concepts de base de la cybersécurité et le paysage technologique associé.</p></div><div><b>Cloud fundamentals</b><p>Découvrir les fondamentaux du cloud et les enjeux de sécurité des environnements cloud.</p></div><div><b>Security concepts &amp; technologies</b><p>Identifier les principales notions et technologies de sécurité utilisées pour protéger systèmes, réseaux et données.</p></div><div><b>Suite du parcours Fortinet</b><p>Cette formation constitue une base pour progresser vers les niveaux et formations techniques suivants du programme Fortinet.</p></div></div><a href="assets/fortinet-cloud.jpg" target="_blank">Voir le certificat ↗</a></div></article>'''
if old not in s: raise SystemExit('cert block not found')
s=s.replace(old,new)
# add a small note under cert title
s=s.replace('Les certificats ne sont pas seulement affichés : leur contenu est détaillé pour montrer les domaines réellement travaillés.</p>', 'Les certificats ne sont pas seulement affichés : leur contenu est détaillé pour montrer les domaines réellement travaillés. Les informations de programme Fortinet sont vérifiées à partir du Training Institute officiel.</p>')
# add modal root before closing body
s=s.replace('</body>', '<div class="room-modal" id="room-modal" aria-hidden="true"><div class="room-modal-panel"><button class="room-modal-close" type="button" aria-label="Fermer">×</button><span class="room-modal-kicker">TRYHACKME · COMPLETED ROOM</span><h3 id="room-modal-title">Room</h3><div class="room-modal-meta"><b id="room-modal-cat">CATEGORY</b><span>✓ COMPLETED</span></div><p id="room-modal-text"></p><div class="room-modal-tags" id="room-modal-tags"></div></div></div></body>')
p.write_text(s)
